### ISSUE TITLE
Server Side Error

### ISSUE THREAD

**Issue by TooLiveAJ** [swkeep/keep-hunting#1]
[   script:qb-hunting] SCRIPT ERROR: @keep-hunting/server/sv_main.lua:113: attempt to call a nil value (global 'Alias_table_wrapper')

**Comment by swkeep** [comment]
Hi, I looked into it, this may happen because "shared/shared.lua" is not loaded correctly, I have two potential solutions for it 
1. check "fxmanifest.lua" file and make sure it contains line below
```lua 
shared_script {'config.lua', 'shared/shared.lua' ,"@qb-core/shared.lua"} 
``` 
2. or copy all "shared.lua" code and paste all of them at the end of "sv_main.lua" (this may not be the best thing to do) and then change "fxmanifest.lua" code like
```lua 
shared_script {'config.lua',"@qb-core/shared.lua"}  
```
